Fix the error when save adv model and use modelcheckpoint callback
tensorflow/neural-structured-learning pull request #114
Opened 2022-05-17 18:44 UTC by wangbingnan136

2022-05-20 04:10 UTC, wangbingnan136 commented
> @wangbingnan136[，你能看一下并在上面的评论](https://github.com/tensorflow/neural-structured-learning/pull/114#issuecomment-1129201056)中签署贡献者许可协议吗？

![image](https://user-images.githubusercontent.com/42114835/169448755-5a19764a-00e2-484a-a0d4-95f4a8c85312.png)
It looks like I have already signed

2022-05-21 17:18 UTC, wangbingnan136 commented
I think the checks were done,sorry this is my first time make a contribution to tensorflow~

2022-05-21 18:39 UTC, csferng requested changes

2022-05-21 18:39 UTC, csferng commented on neural_structured_learning/keras/adversarial_regularization.py
> +from keras.utils import traceback_utils
Please move these two import lines to line 27 (after "import attr") and swap their order. The idea is that the imports from the standard library goes before the imports from third-party libraries, and the imports in the same group are ordered alphabetically.

2022-05-21 18:39 UTC, csferng commented on neural_structured_learning/keras/adversarial_regularization.py
> +from keras.saving import save
What is the earliest version of Keras providing these two modules (`save` and `traceback_utils`)? Please add a line to the [requirements file](https://github.com/tensorflow/neural-structured-learning/blob/master/neural_structured_learning/requirements.txt).

2022-05-21 18:39 UTC, csferng commented on neural_structured_learning/examples/notebooks/Adversarial_regularization_for_image_classification save and load the adv model.ipynb
> +{
<p>Thanks for adding an example notebook. I think it is great to demonstrate the saving and loading functionalities. Please update the title and the overview section to focus on that. Also maybe please rename this file to match the new title.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tensorflow/neural-structured-learning/pull/114/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2022-05-21 18:39 UTC, csferng commented on neural_structured_learning/examples/notebooks/Adversarial_regularization_for_image_classification save and load the adv model.ipynb
> +{
<p>How about adding some evaluation to demonstrate that the loaded model performs the same as the model before saving?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tensorflow/neural-structured-learning/pull/114/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='43'/>

2022-05-22 07:42 UTC, wangbingnan136 commented
ok,I got it!

2022-05-25 10:19 UTC, wangbingnan136 commented
It is done

2022-05-27 04:39 UTC, csferng commented
Thanks for the fix! Let me polish the example notebook a bit before merging the PR.

2022-05-27 06:35 UTC, wangbingnan136 commented
Okk

2022-05-27 06:37 UTC, wangbingnan136 commented
I found that when we load the model，the "fit" and "predict" methods works as expected.But the "evalaute" has some bugs.I will fix this problem when I am not busy.

2022-06-09 00:38 UTC, csferng commented
Sorry for the delay. I made some updates on the notebook and will proceed to merge this PR.

Regarding the bug on `evaluate`, what I encountered is that the accuracy number was off for the loaded model (`0.09` vs. `0.98`). The root cause turns out to be that `metrics=['acc']` is interpreted differently. (Keras has some internal heuristic to distinguish what "accuracy" means to a model.) What we expect is `tf.keras.metrics.SparseCategoricalAccuracy`, which is the case for the `adv_model`. But the loaded model somehow got `tf.keras.metrics.CategoricalAccuracy`, so the evaluation result became different.  To workaround this issue, I changed `metrics=['acc']` to `metrics=[tf.keras.metrics.SparseCategoricalAccuracy()]`, which then produced consistent result before and after saving/loading.

2022-06-10 17:17 UTC, merged